/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiFilesRouteImport } from './routes/api/files_'
import { Route as ApiInfoRouteImport } from './routes/api/info'
import { Route as ApiRpcRouteImport } from './routes/api/rpc'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'
import { Route as DocDocumentIdRouteImport } from './routes/doc.$documentId'
import { Route as SubjectsIndexRouteImport } from './routes/subjects.index'
import { Route as SubjectsSubjectIdRouteImport } from './routes/subjects.$subjectId'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files_.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files_',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInfoRoute = ApiInfoRouteImport.update({
  id: '/api/info',
  path: '/api/info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcRoute = ApiRpcRouteImport.update({
  id: '/api/rpc',
  path: '/api/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const DocDocumentIdRoute = DocDocumentIdRouteImport.update({
  id: '/doc/$documentId',
  path: '/doc/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdRoute = SubjectsSubjectIdRouteImport.update({
  id: '/subjects/$subjectId',
  path: '/subjects/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiFilesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/info': typeof ApiInfoRoute
  '/api/rpc': typeof ApiRpcRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/doc/$documentId': typeof DocDocumentIdRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/chat/': typeof ChatIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/api/files/$': typeof ApiFilesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/files': typeof ApiFilesRouteWithChildren
  '/api/info': typeof ApiInfoRoute
  '/api/rpc': typeof ApiRpcRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/doc/$documentId': typeof DocDocumentIdRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/chat': typeof ChatIndexRoute
  '/subjects': typeof SubjectsIndexRoute
  '/api/files/$': typeof ApiFilesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/files_': typeof ApiFilesRouteWithChildren
  '/api/info': typeof ApiInfoRoute
  '/api/rpc': typeof ApiRpcRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/doc/$documentId': typeof DocDocumentIdRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRoute
  '/chat/': typeof ChatIndexRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/api/files_/$': typeof ApiFilesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/api/chat'
    | '/api/files'
    | '/api/info'
    | '/api/rpc'
    | '/chat/$threadId'
    | '/doc/$documentId'
    | '/subjects/$subjectId'
    | '/chat/'
    | '/subjects/'
    | '/api/files/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/files'
    | '/api/info'
    | '/api/rpc'
    | '/chat/$threadId'
    | '/doc/$documentId'
    | '/subjects/$subjectId'
    | '/chat'
    | '/subjects'
    | '/api/files/$'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/api/chat'
    | '/api/files_'
    | '/api/info'
    | '/api/rpc'
    | '/chat/$threadId'
    | '/doc/$documentId'
    | '/subjects/$subjectId'
    | '/chat/'
    | '/subjects/'
    | '/api/files_/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiFilesRoute: typeof ApiFilesRouteWithChildren
  ApiInfoRoute: typeof ApiInfoRoute
  ApiRpcRoute: typeof ApiRpcRoute
  DocDocumentIdRoute: typeof DocDocumentIdRoute
  SubjectsSubjectIdRoute: typeof SubjectsSubjectIdRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files_': {
      id: '/api/files_'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/info': {
      id: '/api/info'
      path: '/api/info'
      fullPath: '/api/info'
      preLoaderRoute: typeof ApiInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc': {
      id: '/api/rpc'
      path: '/api/rpc'
      fullPath: '/api/rpc'
      preLoaderRoute: typeof ApiRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/doc/$documentId': {
      id: '/doc/$documentId'
      path: '/doc/$documentId'
      fullPath: '/doc/$documentId'
      preLoaderRoute: typeof DocDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId': {
      id: '/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof SubjectsSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files_/$': {
      id: '/api/files_/$'
      path: '/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof ApiFilesRoute
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface ApiFilesRouteChildren {
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
}

const ApiFilesRouteChildren: ApiFilesRouteChildren = {
  ApiFilesSplatRoute: ApiFilesSplatRoute,
}

const ApiFilesRouteWithChildren = ApiFilesRoute._addFileChildren(
  ApiFilesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiFilesRoute: ApiFilesRouteWithChildren,
  ApiInfoRoute: ApiInfoRoute,
  ApiRpcRoute: ApiRpcRoute,
  DocDocumentIdRoute: DocDocumentIdRoute,
  SubjectsSubjectIdRoute: SubjectsSubjectIdRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
