import type { SVGProps } from "react";

export type LoaderOutline18Props = SVGProps<SVGSVGElement> & {
  strokeWidth?: number | string;
};

export function LoaderOutline18({ strokeWidth = 1.5, ...props }: LoaderOutline18Props) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width={18} height={18} viewBox="0 0 18 18" {...props}>
      <line
        x1="9"
        y1="1.75"
        x2="9"
        y2="4.25"
        fill="none"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></line>
      <line
        x1="14.127"
        y1="3.873"
        x2="12.359"
        y2="5.641"
        fill="none"
        opacity=".88"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></line>
      <line
        x1="16.25"
        y1="9"
        x2="13.75"
        y2="9"
        fill="none"
        opacity=".75"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></line>
      <line
        x1="14.127"
        y1="14.127"
        x2="12.359"
        y2="12.359"
        fill="none"
        opacity=".63"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></line>
      <line
        x1="9"
        y1="16.25"
        x2="9"
        y2="13.75"
        fill="none"
        opacity=".5"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></line>
      <line
        x1="3.873"
        y1="14.127"
        x2="5.641"
        y2="12.359"
        fill="none"
        opacity=".38"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></line>
      <line
        x1="1.75"
        y1="9"
        x2="4.25"
        y2="9"
        fill="none"
        opacity=".25"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></line>
      <line
        x1="3.873"
        y1="3.873"
        x2="5.641"
        y2="5.641"
        fill="none"
        opacity=".13"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={strokeWidth}
      ></line>
    </svg>
  );
}
